### ISSUE TITLE
./build/run-fpm.sh in inference-engine/cloud-microphysics does not run

### ISSUE THREAD

**Issue by davytorres** [BerkeleyLab/inference-engine#117]
./setup.sh runs under directories inference-engine and inference-engine/cloud-microphysics

However ./build/run-fpm.sh run train-cloud-microphysics -- --base training --epochs 10 --start 720 

does not run in inference-engine/cloud-microphysics

**Comment by rouson** [comment]
@davytorres I believe this has been fixed on main so I'm closing this.  Let me know if you still see the problem.
