### ISSUE TITLE
Segmentation fault when running examples on main branch

### ISSUE THREAD

**Issue by davytorres** [BerkeleyLab/inference-engine#168]
For some reason, when I clone the main branch, I get a segmentation fault when I run the examples (e.g. learn-addition) using gfortran version 14.1.0.

fpm run --example learn-addition --profile release --flag "-fopenmp" -- --output-file "test-addition-output"

**Comment by rouson** [comment]
@davytorres I think this has been fixed so I'm closing the issue.  Let me know if you still see the problem.
