### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [BerkeleyLab/inference-engine#44]
I suggest adding topics such as `ann`, `neural-network`, `feedforward-neural-network` in the About section at https://github.com/BerkeleyLab/inference-engine

**Comment by rouson** [comment]
@Beliavsky thanks for these suggestions.  I added these a while back but forgot to close this issue so I'm doing this now.  If you have any interest in using Inference-Engine and would like to provide examples of what you're interested in doing and what features would be useful, feel free to let me know.  This work is not currently funded, but my interest remains and some collaborators are helping to move things forward on their own funding.
