### ISSUE TITLE
Issue Compiling with ifx

### ISSUE THREAD

**Issue by everythingfunctional** [BerkeleyLab/inference-engine#61]
Here's the error I get trying to compile with ifx:

```text
layer_s.f90                            failed.
[ 57%] Compiling...
././src/inference_engine/layer_s.f90(22): error #6197: An assignment of different structure types is invalid.   [CONSTRUCT]
    layer%neuron = neuron_t(layer_lines, start+1)
-------------------^
```

**Comment by rouson** [comment]
Thanks, @everythingfunctional.  I'll work on isolating a reproducer.  How would you recommend submitting this to Intel?  Shall I submit a NERSC bug report or submit it to the reproducer repository you set up recently or both?

**Comment by everythingfunctional** [comment]
I'd like to start using the reproducer repo more broadly, so if you could put it there that would be great. As for how to submit to Intel, I don't think they are currently a vendor of NERSC (i.e. any support for oneAPI on Perlmutter is "experimental"/"unofficial"), so might be better to submit as Archaeologic.

**Comment by rouson** [comment]
@ktras I'll close this for now. This was a couple of compiler releases ago so the issues with `ifx` are likely different now.  Let's talk about the best way to track compiler bug reports.

**Comment by ktras** [comment]
@rouson Sounds good. I am working on a way to track compiler bugs we submit, as well as which portion of our software (inference-engine, cloud-microphysics, or icar-with-inference-engine-dependency) works currently with which versions of which compilers.
